version: '3'

services:
  client:
    container_name: vue
    build:
      context: .
      dockerfile: ./build/client/Dockerfile
    ports:
      - 8080:8080
    volumes: 
      - ./src/client:/root/client
    tty: true